[package]
name = "glide"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
glide_codegen = { path = "../glide_codegen" }
glide_compiler = { path = "../glide_compiler" }
glide_parser = { path = "../glide_parser" }
glide_span = { path = "../glide_span" }
